test:
  servers: "127.0.0.1:9160"
  keyspace: "socialtango_development"
  thrift:
    timeout: 3
    retries: 2

development:
  servers: "127.0.0.1:9160"
  keyspace: "socialtango_development"
  thrift:
    timeout: 3
    retries: 2